### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by ettorerizza** [wetneb/openrefine-wikidata#14]
Hi Antonin,

I finally had the opportunity to test the reconciliation intensively: it's great work :) For now, the only remark that comes to my mind concerns the scoring of ex-aequo. For the French month "Avril", for example, I have four candidates who each have 100% probability. The first three are "Avril" and the fourth "Avril Lavigne". I wonder if we should not penalize candidates whose distance Levenshtein exceeds a certain threshold, something like that. For the rest, thank you again !

Yours,

**Comment by wetneb** [comment]
Hi @ettorerizza ,

This behavior generally appears when some alias of the item is a perfect match with the query. In your case, https://www.wikidata.org/wiki/Q30449 has "Avril" as alias in Swedish, so that is a perfect match. We currently treat all aliases and labels in any language equally (the language you select when installing the reconciliation interface only determines in which language we display labels).

It would be straightforward to change that and only consider labels for the language you selected when installing the reconciliation interface (English by default) but that would make it harder to deal with OpenRefine projects where the language varies.

I agree it is a problem and would be very interested to hear any suggestions! Maybe matches against aliases should be discounted?

Anyway for your particular use case I suggest you restrict the reconciliation by type, which should solve this particular issue.

**Comment by ettorerizza** [comment]
OK, I understand better. In this case it is not a bug, it is a feature, since the great advantage of Wikidata on DBpedia is its linguistic agnosticism. Now I am working on a project that consists in checking the quality of reconciliations with Wikidata on user searches in a database. Those queries are multilingual and do not concern any particular topic, so I am forced to use "Reconcile against no particular type". 

I will try to find a way to break the ties. Thank you for your prompt response !

**Comment by ettorerizza** [comment]
If this may interest someone else, here is the Jython solution I used to assign each candidate an edit distance from the original term.

```
def call_counter(func):
    def helper(*args, **kwargs):
        helper.calls += 1
        return func(*args, **kwargs)
    helper.calls = 0
    helper.__name__= func.__name__
    return helper
memo = {}
@call_counter
def levenshtein(s, t):
    if s == "":
        return len(t)
    if t == "":
        return len(s)
    cost = 0 if s[-1] == t[-1] else 1
       
    i1 = (s[:-1], t)
    if not i1 in memo:
        memo[i1] = levenshtein(*i1)
    i2 = (s, t[:-1])
    if not i2 in memo:
        memo[i2] = levenshtein(*i2)
    i3 = (s[:-1], t[:-1])
    if not i3 in memo:
        memo[i3] = levenshtein(*i3)
    res = min([memo[i1]+1, memo[i2]+1, memo[i3]+cost])
    return res

candidates_edit = []
for i in cell['recon']['candidates']:
    candidates_edit.append(str(levenshtein(value, i.name)))

return "|".join(candidates_edit)
```

**Result :**
![sans titre 1](https://user-images.githubusercontent.com/6286410/27002036-a0e25b72-4dd7-11e7-8ae6-df3462adb9f5.jpg)
