### ISSUE TITLE
Compatibility with Google Refine 2.5

### ISSUE THREAD

**Issue by fokky** [wetneb/openrefine-wikidata#5]
Hi - thank you SO MUCH for implementing this service. I have been waiting for it for a very long time!

I wanted to test it with a small dataset, but can't get it to work. Here's my process:

I scraped the member section of http://www.kvab.be/ (the Flemish Academy of Science - has many notable members). (The dataset is in Mix'n'Match too, see http://tools.wmflabs.org/mix-n-match/?mode=catalog_details&catalog=359 - there I got 90 matches with Wikidata).

Added the data to OpenRefine and cleaned it a bit.
![image](https://cloud.githubusercontent.com/assets/9881645/22681779/563b843c-ed0f-11e6-86f0-a8b4d6c8877c.png)
The data I'm working with is this: https://drive.google.com/open?id=0B9jfaELxxRSxU2hadzJJZGxleTg

Now I want to reconcile the names in the 'persoon 1' column. (I'm absolutely certain that many of these are on Wikidata)

Starting the reconciliation service:
![image](https://cloud.githubusercontent.com/assets/9881645/22681837/ade5e9f2-ed0f-11e6-8c00-082f9cd7fdb6.png)

I think here it goes wrong already? I get no automatic type suggestions like in the example you provided yourself at https://tools.wmflabs.org/openrefine-wikidata/.
![image](https://cloud.githubusercontent.com/assets/9881645/22681861/dc39618a-ed0f-11e6-8c07-9e6e5c600eb6.png)

When I type anything in the 'reconcile against type' box, it just keeps saying 'searching....', producing no results. I try with human, Q5, makes no difference.
![image](https://cloud.githubusercontent.com/assets/9881645/22681894/083fd2d2-ed10-11e6-91b7-7fc1d77a8d61.png)

For now, I have just typed Q5 there and continue with the reconciliation itself.

It's busy now. Takes a few minutes for 233 names.
![image](https://cloud.githubusercontent.com/assets/9881645/22681927/38cd9f74-ed10-11e6-836d-2d754b5ff905.png)

And the results: no matches, unfortunately. Although I'm quite certain that quite a few of these names have (exact and unique) matches on Wikidata.
![image](https://cloud.githubusercontent.com/assets/9881645/22681971/8485db52-ed10-11e6-809f-9588badebc6f.png)

For instance, Katlijne van der Stighelen has an exact and unique match:
![image](https://cloud.githubusercontent.com/assets/9881645/22681999/aaf221d8-ed10-11e6-8d88-80e386964c11.png)

But even when doing the 'search for match' function, OpenRefine keeps hanging on search.
![image](https://cloud.githubusercontent.com/assets/9881645/22682022/c8bfe83a-ed10-11e6-800c-ed34341d0eaa.png)

Now I'm wondering if this is an error on my side? Am I doing something wrong in the process? Or do others have the same issue? I have noticed earlier that my Chrome browser does act strange sometimes. Thanks!

**Comment by fokky** [comment]
By the way, I also get no matches when I select 'Reconcile against no particular type'.

**Comment by wetneb** [comment]
@fokky Thank you so much for this extremely detailed bug report. I will investigate.

**Comment by wetneb** [comment]
It's curious, because it works pretty well for me… Can you remove the endpoint and add it again? It is now possible to choose a preferred language to display items and properties, as explained on
https://tools.wmflabs.org/openrefine-wikidata/

Otherwise I would be interested to have your OpenRefine logs: they should show HTTP errors. One way to read them is to start OpenRefine from the console, by typing "./refine" in the OpenRefine directory: the logs will display below.

Also, which version of OpenRefine are you using? Yours seem to indicate "Google Refine" instead of "OpenRefine" here. I have tested the interface with the latest version (beta 2.6 rc2). I will try with the stable version soon.

![worksforme](https://cloud.githubusercontent.com/assets/309908/22688019/59b784ae-ed22-11e6-83ac-1a1266570d8a.png)

**Comment by fokky** [comment]
Thanks for your quick comments! In my original example, I used Google Refine 2.5 indeed. Now I have switched to OpenRefine 2.6 rc 2 and yes, it works!
